package functions

import (
	"functions/app"
	"log"
)

var application *app.App

func init() {
	config := GetAutogeneratedConfig()

	var err error
	application, err = app.Init(config)

	if err != nil {
		log.Fatalf("Cannot initialize app: %v", err)
	}
}
